### ISSUE TITLE
TypeError: _obtain_input_shape() got an unexpected keyword argument 'include_top'

### ISSUE THREAD

**Issue by alyato** [adamcasson/resnet152#1]
@adamcasson  when i call the resnet152, it show that
`base_model = ResNet152(classes=8)`

**Comment by ChristofHenkel** [comment]
change line 262 - 266 to:

    input_shape = _obtain_input_shape(input_shape,
                                      default_size=img_size,
                                      min_size=197,
                                      data_format=K.image_data_format(),
                                      require_flatten=False)

Fixed it for me at least

**Comment by estathop** [comment]
Using TensorFlow backend.
Traceback (most recent call last):

  File "<ipython-input-1-9eddf8fa979b>", line 4, in <module>
    from resnet152 import ResNet152

  File "resnet152.py", line 37, in <module>
    from keras.applications.imagenet_utils import _obtain_input_shape

ImportError: cannot import name _obtain_input_shape

**Comment by estathop** [comment]
what @ChristofHenkel said didn't fix the issue for me

**Comment by estathop** [comment]
switching from keras 2.2.2 to 2.0.0 didn't solve the issue for me

**Comment by estathop** [comment]
the initial code in this repo with tensorflow 2.0.0 works though. It is better to consider a downgrade on this case

**Comment by edumucelli** [comment]
My PR #2 fixes that issue.

**Comment by adamcasson** [comment]
Merged PR from @edumucelli should fix
